### ISSUE TITLE
Add actors and transactions

### ISSUE THREAD

**Issue by bdc-ehealth** [hl7-be/public-health#10] opened 2022-10-25 09:01 UTC
@kridhaen

Hi Kurt,

can you provide a list with actors and transactions in the style:

Transaction 1: send episode to Vitalink
Sender: Hercules
Receiver: Vitalink
Input: bundle with EpisodeOfCare, Encounter, ... (to be completed and detailed)
Output: acknowledment of receipt or error message or nothing (in case of Byzantine error)

Transaction 2: update episode already present in Vitalink
Sender: ...
....

Do you see what I mean?

**Comment by bdc-ehealth** [comment] 2022-11-22 09:34
WG: @kridhaen agrees to do this.

**Comment by kridhaen** [comment] 2022-12-05 13:32
# Use cases
## Short summary of different use cases in Heracles based on the logical model with possible actions on FHIR resources:
- Send invitation to Vitalink
    - EpisodeOfCare exists in Vitalink?
        - Yes: 
            - Update nextInvitationIndication -> Update EpisodeOfCare
            - Add invitation -> Add Appointment
        - No:
            - Update nextInvitationIndication -> Create EpisodeOfCare
            - Add invitation -> Add Appointment
- Result of Heracles episode reached / end state of Heracles episode reached
    - EpisodeOfCare exists in Vitalink?
        - Yes: 
            - Update nextInvitationIndication -> Update EpisodeOfCare
            - Add participation -> Add Encounter
            - Add result -> Add Observation
            - Optional: Add followup -> Add ServiceRequest
        - No:
            - Update nextInvitationIndication -> Create EpisodeOfCare
            - Add participation -> Add Encounter
            - Add result -> Add Observation
            - Optional: Add followup -> Add ServiceRequest
- Rollback of Heracles episode state OR delete participation:
    - Update nextInvitationIndication -> Update EpisodeOfCare
    - Delete participation -> Delete Encounter
    - Delete result -> Delete Observation
    - Delete followup -> Delete ServiceRequest
- Delete invitation:
    - Update nextInvitationIndication -> Update EpisodeOfCare
    - Delete invitation -> Delete Appointment
- Delete Heracles episode:
    - Delete episode -> Delete EpisodeOfCare
    - Delete invitation -> Delete participation
    - Delete participation -> Delete Encounter
    - Delete result -> Delete Observation
    - Delete followup -> Delete ServiceRequest
    - Previous Heracles episode exists?
        - Yes:
            - Update nextInvitationIndication of previous episode -> Update EpisodeOfCare
        - No:
            - Person has refusal or exclusion?
                - Yes:
                    - Update nextInvitationIndication -> Create EpisodeOfCare
                - No:
                    - /
- Refusal or Exclusion registered or updated:
    - EpisodeOfCare exists?
        - Yes:
            - Update nextInvitationIndication -> Update EpisodeOfCare
        - No:
            - Update nextInvitationIndication -> Create EpisodeOfCare
- Refusal or Exclusion deleted:
    - Person has other refusal/exclusion or invitation/participation?
        - Yes:
            - Update nextInvitationIndication -> Update EpisodeOfCare
        - No:
            - Remove episode -> Delete EpisodeOfCare
- Data exchange with Vitalink not allowed:
    - Delete everything
- Data exchange with Vitalink allowed again:
    - Recreate everything

## Use cases mapped to FHIR resources:
\* Resources in budle are updates or creates, unless otherwise specified.

\*\* Not all resources specified with delete will always be available in the use case. If it does not exist, it will not be provided in the bundle.

- Transaction 1: send episode to Vitalink OR update nextInvitationIndication
    - Sender: Heracles
    - Receiver: Vitalink
    - Input: bundle with EpisodeOfCare
    - Output: acknowledment of receipt or error message or nothing (in case of Byzantine error)
- Transaction 2: send invitation to Vitalink
    - Sender: Heracles
    - Receiver: Vitalink
    - Input: bundle with EpisodeOfCare, Appointment
    - Output: acknowledment of receipt or error message or nothing (in case of Byzantine error)
- Transaction 3: send participation to Vitalink
    - Sender: Heracles
    - Receiver: Vitalink
    - Input: bundle with EpisodeOfCare, Encounter, Observation
    - Output: acknowledment of receipt or error message or nothing (in case of Byzantine error)
- Transaction 4: send participation with follow-up to Vitalink 
    - Sender: Heracles
    - Receiver: Vitalink
    - Input: bundle with EpisodeOfCare, Encounter, Observation, ServiceRequest
    - Output: acknowledment of receipt or error message or nothing (in case of Byzantine error)
- Transaction 5: delete participation from Vitalink
    - Sender: Heracles
    - Receiver: Vitalink
    - Input: bundle with EpisodeOfCare, delete Encounter, delete Observation, delete ServiceRequest
    - Output: acknowledment of receipt or error message or nothing (in case of Byzantine error)
- Transaction 6: delete invitation from Vitalink
    - Sender: Heracles
    - Receiver: Vitalink
    - Input: EpisodeOfCare, delete Appointment
    - Output: acknowledment of receipt or error message or nothing (in case of Byzantine error)
- Transaction 7: delete episode from Vitalink, but nextInvitationIndication should be updated
    - Sender: Heracles
    - Receiver: Vitalink
    - Input: bundle with EpisodeOfCare, delete EpisodeOfCare, delete Appointment, delete Encounter, delete Observation, delete ServiceRequest
    - Output: acknowledment of receipt or error message or nothing (in case of Byzantine error)
- Transaction 8: delete episode from Vitalink
    - Sender: Heracles
    - Receiver: Vitalink
    - Input: delete EpisodeOfCare, delete Appointment, delete Encounter, delete Observation, delete ServiceRequest
    - Output: acknowledment of receipt or error message or nothing (in case of Byzantine error)
- Transaction 9: send complete episode to Vitalink
    - Sender: Heracles
    - Receiver: Vitalink
    - Input: EpisodeOfCare, Appointment, Encounter, Observation, ServiceRequest
    - Output: acknowledment of receipt or error message or nothing (in case of Byzantine error)

## Assumptions
- The nextInvitationIndication from the logical model is mapped by the EpisodeOfCare (e.g. as an extention.). Almost every time an action in Heracles occurs that will be shared with Vitalink, the nextInvitationIndication will change. If the nextInvitationIndication is mapped by another resource, the resource will be provided in the input bundle so it can be created/updated.

## Questions
- Create and update can happen in the same transaction? If the resource with the given identifier is known by Vitalink, the resource will be updated, otherwise created?
- Deletes can happen in the same transaction?
- Will Vitalink use soft deletes? Use case patient notifies Heracles that data exchange with Vitalink is not allowed, so the data should not be visible in Vitalink anymore. If the patient notifies Heracles some time later that data exchange is allowed again, can Vitalink undo the deletes or should we just send everything again so it can be recreated?

**Comment by costateixeira** [comment] 2022-12-05 13:41
Note that our 'transactions' are not as DB transactions. DB transactions
are more about an unbreakable set of operations.
Our transactions are more like interactions.

**Comment by bdc-ehealth** [comment] 2022-12-05 14:28
@kridhaen ,

Hello Kurt,

I see that you always plan to send the EpisodeOfCare as a base resource or starting point for other references in a Bundle to Vitalink. Does this mean that you will never send Appointments, Encounters, Observations, ServiceRequests alone to Vitalink?

Second question: Will you use a synchronous protocol (probably HTTP/REST) or an asynchronous protocol (Message-based or document based) to send the messages?

**Comment by kridhaen** [comment] 2022-12-05 14:55
@bdc-ehealth 
- First question: This is based on the assumption above. In almost all cases, the nextInvitationIndication from the logical model changes when we know more about the state of the current screening. This change in nextInvitationIndication will need to be shared with Vitalink. Our initial idea is to map this nextInvitationIndication as extension on EpisodeOfCare, but if there are better alternatives, this can change (see https://github.com/hl7-be/public-health/issues/8).

    To give an idea of the current content of nextInvitationIndication used in KMEHR, see the table below (This table is used internally by Heracles to determine the text for nextInvitationIndication in KMEHR. These values are not confirmed for FHIR.). In https://github.com/hl7-be/public-health/issues/8 we concluded that we would like to use a code and in some cases in combination with a date to better represent the nextInvitationIndication currently used in KMEHR. (In some cases we currently have a template with a date. In FHIR, we will have codes and those dates will be in a date field and not in the code or translation.) Looking at the table, we see that when a petient gets an invitation or participates, the nextInvitationIndication changes. That's why for almost all actions, we will update the nextInvitationIndication and depending on what resource this is represented by in FHIR, we will update that resource. If this will be the EpisodeOfCare, we will need to always update the EpisodeOfCare. So we will probably never send an Appointment, Encounter, etc alone, because the resource that represents the nextInvitationIndication will also need to be updated.

<html>
<body>


Type | Template
-- | --
VOLGENDE_UITNODIGING | De volgende uitnodiging is voorzien rond %1$s.
DEFINITIEF_UITGESLOTEN | Je ontvangt geen volgende uitnodiging meer.
NIET_IN_DOELGROEP | Je ontvangt geen volgende uitnodiging. De leeftijdsgroep voor dit bevolkingsonderzoek start vanaf het jaar waarin je 50 jaar wordt en loopt tot en met het jaar waarin je 69 jaar wordt.
WEIGERING | Je ontvangt geen volgende uitnodiging omdat je hebt laten weten dat je geen uitnodiging meer wou ontvangen. Indien je meer informatie wenst over dit onderzoek kan je dit best bespreken met je arts.
TIJDELIJK_UITGESLOTEN | Volgens onze gegevens is dit onderzoek voor jou op dit moment niet nodig of niet aangewezen. Daarom ontvang je tijdelijk geen uitnodigingen meer. De volgende uitnodiging is voorzien rond %1$s. Indien je hierover meer wenst te weten, kan je dit bespreken met je arts.
ONDUIDELIJK | De datum van volgende uitnodiging is afhankelijk van de uitslag van het verdere onderzoek.
ONGEDEFINIEERD | We kunnen niet bepalen wanneer u de volgende keer zal uitgenodigd worden.


</body>
</html>

- For the second question: We will probably use HTTP/REST, but this is not confirmed and will depent on what Vitalink allows or provides.

**Comment by costateixeira** [comment] 2022-12-20 09:56
We agree that we'll have one transaction to start - update the cancer screening information.
We can later add more transactions but those are not expected not impact the profiles significantly.

**Comment by costateixeira** [comment] 2022-12-20 10:00
We will document the transaction including the use of any grouping mechanism e.g Bundle.

**Comment by bdc-ehealth** [comment] 2023-01-10 09:29
WG: we provide diagram (sequence style diagram) with the two actors and the transaction. The acknowledgement is provided whatever the standard provides.

**Closed as completed** 2023-01-11 11:23 UTC
